### PR TITLE
MAINT: switch dirs from klauer home to shared area, no more reg

### PR DESCRIPTION
**Pull request by ZLLentz**
after making this PR I'm going to set my psbuild-rhel7-01 crontab based on this branch

### CODE REVIEW

**Review by klauer — APPROVED** [review]
Changes look good so far. Let's see how they fare when actually run from someone else's account...

**Comment by ZLLentz** [comment]
So far we've got this for the confluence ones:
```
requests.exceptions.HTTPError: Could not update Content of type : class com.atlassian.confluence.pages.Page with id 337065852
```

And this for the github ones:
```
Permission denied (publickey).
```

**Comment by ZLLentz** [comment]
I made a short modification to the confluence tokens thing to try putting in the `export CONFLUENCE_URL=` line that I thought was bonus from the example. Maybe I need to put a specific url here?

For the ssh-to-github thing I assume I need to do something special

**Comment by klauer** [comment]
I think setting `CONFLUENCE_URL` isn't necessary at the moment - looks like it's hard-coded.

Not sure about this message:
```
requests.exceptions.HTTPError: Could not update Content of type : class com.atlassian.confluence.pages.Page with id 337065852
```
That's [this page](https://confluence.slac.stanford.edu/pages/viewpage.action?pageId=337065852) so `update_all_iocs.sh` isn't working. Does that happen on the other pages as well?

**Comment by klauer** [comment]
Update: it was page permissions related and the Confluence API exception was not helpful.

**Comment by ZLLentz** [comment]
I think the rest of this will be github auth-related and will either be not related to the contents of this repo or in a separate PR

**Pull request merged**
